version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.ajoberstar:gradle-git-publish
    versions:
    - ">= 0"
  - dependency-name: org.mockito:mockito-core
    versions:
    - 2.x
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-convenience
    versions:
    - 1.56.0
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-models
    versions:
    - 1.56.0
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-java-client
    versions:
    - 1.56.0
