version: 1
update_configs:
  - package_manager: java:gradle
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*"
    ignored_updates:
      - match:
          dependency_name: "org.mockito:mockito-core"
          version_requirement: "2.x"
      - match:
          dependency_name: "org.ajoberstar:gradle-git-publish"
