# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: serializing workflow runs
      uses: softprops/turnstyle@v1
      with:
        same-branch-only: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build with Gradle
      run: ./gradlew ciBuild gitPublishPush
      env:
        CT_CLIENT_ID: ${{ CT_CLIENT_ID }}
        CT_CLIENT_SECRET: ${{ CT_CLIENT_SECRET }}
        CT_PROJECT_KEY: ${{ CT_PROJECT_KEY }}
        TENANTS: TEST_DATA
        TEST_DATA_TENANT_NAME: ${{ TEST_DATA_TENANT_NAME }}
        TEST_DATA_TENANT_NAME_2: ${{ TEST_DATA_TENANT_NAME_2 }}
        CT_PAYONE_INTEGRATION_URL: ${{ CT_PAYONE_INTEGRATION_URL }}
    - name: Codecov
      uses: codecov/codecov-action@v1
