# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: serializing workflow runs
      uses: softprops/turnstyle@v1
      with:
        same-branch-only: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Build with Gradle
      run: ./gradlew setLibraryVersion ciBuild gitPublishPush
      env:
        CT_CLIENT_ID: ${{ secrets.CT_CLIENT_ID }}
        CT_CLIENT_SECRET: ${{ secrets.CT_CLIENT_SECRET }}
        CT_PROJECT_KEY: payone-integration-tests-heroku-17
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TEST_DATA_3_DS_PASSWORD: ${{ secrets.TEST_DATA_3_DS_PASSWORD }}
        TEST_DATA_CT_CLIENT_ID: ${{ secrets.TEST_DATA_CT_CLIENT_ID }}
        TEST_DATA_CT_CLIENT_ID_2: ${{ secrets.TEST_DATA_CT_CLIENT_ID_2 }}
        TEST_DATA_CT_CLIENT_SECRET: ${{ secrets.TEST_DATA_CT_CLIENT_SECRET }}
        TEST_DATA_CT_CLIENT_SECRET_2: ${{ secrets.TEST_DATA_CT_CLIENT_SECRET_2 }}
        TEST_DATA_CT_PAYONE_INTEGRATION_URL: https://ct-payone-integration-staging.herokuapp.com
        TEST_DATA_CT_PROJECT_KEY: payone-integration-tests-heroku-17
        TEST_DATA_CT_PROJECT_KEY_2: payone-integration-tests
        TEST_DATA_PAYONE_KEY: ${{ secrets.TEST_DATA_PAYONE_KEY }}
        TEST_DATA_PAYONE_KEY_2: ${{ secrets.TEST_DATA_PAYONE_KEY_2 }}
        TEST_DATA_PAYONE_MERCHANT_ID: 31102
        TEST_DATA_PAYONE_MERCHANT_ID_2: 31102
        TEST_DATA_PAYONE_PORTAL_ID: 2022125
        TEST_DATA_PAYONE_PORTAL_ID_2: 2026522
        TEST_DATA_PAYONE_SUBACC_ID: 31281
        TEST_DATA_PAYONE_SUBACC_ID_2: 31281
        TEST_DATA_TENANT_NAME: FIRST_TENANT
        TEST_DATA_TENANT_NAME_2: SECOND_TENANT
        CT_PAYONE_INTEGRATION_URL: https://ct-payone-integration-staging.herokuapp.com
        TEST_DATA_VISA_CREDIT_CARD_3DS: ${{ secrets.TEST_DATA_VISA_CREDIT_CARD_3DS }}
        TEST_DATA_VISA_CREDIT_CARD_NO_3DS: ${{ secrets.TEST_DATA_VISA_CREDIT_CARD_NO_3DS }}
